### ISSUE TITLE
HTML parser: comment introduces a span element

### ISSUE THREAD

**Issue by MuthuChess** [remarkjs/react-markdown#454]
Hi,

While rendering the below markdown, a span gets introduced under anchor tag because of the comment. The highlighted code can be tested directly at https://rexxars.github.io/react-markdown/
 
```
# Overview

<!-- Please do not change this html logo with link -->

<a href="https://rexxars.github.io/" rel="nofollow"><img src="images/test.png" alt="React Markdown" width="300"/></a>
```
 
![image](https://user-images.githubusercontent.com/35551343/89771839-a27fae80-db1e-11ea-9feb-c170d9e1be19.png)

### Without the comment it renders properly

```
# Overview

<a href="https://rexxars.github.io/" rel="nofollow"><img src="images/test.png" alt="React Markdown" width="300"/></a>
```
 
![image](https://user-images.githubusercontent.com/35551343/89771756-76642d80-db1e-11ea-8c55-9666a7b00e98.png)

Please suggest how to discard the span introduced between a tag and img.

Regards,
Muthu.

**Comment by ChristianMurphy** [comment]
The issue is likely with https://github.com/rexxars/react-markdown/blob/master/src/plugins/html-parser.js
This for example does not add an extra span

```markdown
# Overview

<!-- Please do not change this html logo with link -->

<a href="https://rexxars.github.io/" rel="nofollow">
  <img src="images/test.png" alt="React Markdown" width="300"/>
</a>
```

https://github.com/rexxars/react-markdown/pull/428 will resolve this issue.

**Comment by wooorm** [comment]
This should be solved by landing GH-563 today, which will soon be released in v6.0.0!

**Comment by factoidforrest** [comment]
This is still an issue for me, with comments getting dumped out right into the text on the page, including the <!-- tag.  Just wanted to chime in that I was able to fix it using 
```remark-remove-comments```
which just takes out that part of markdown before it hits the HTML generation step.  Rehype-remove-comments did not work, interestingly.

**Comment by wooorm** [comment]
That is unrelated to this old issue. How to deal with HTML in markdown is documented in the readme: https://github.com/remarkjs/react-markdown#appendix-a-html-in-markdown
