### ISSUE TITLE
Table failed in remark-gfm@4.0.0 ( released just now) 

### ISSUE THREAD

**Issue by AndyBoat** [remarkjs/react-markdown#771]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

8.0.7

### Link to runnable example

https://codesandbox.io/s/distracted-euler-qy4rp9?file=/src/App.js

### Steps to reproduce

Run the codesandbox exmaple and you will see error thrown:
```
TypeError
Cannot set properties of undefined (setting 'inTable')

Object.enterTable
https://qy4rp9.csb.app/node_modules/mdast-util-gfm-table/lib/index.js:38:21
compile
https://qy4rp9.csb.app/node_modules/mdast-util-from-markdown/lib/index.js:157:40
fromMarkdown
https://qy4rp9.csb.app/node_modules/mdast-util-from-markdown/lib/index.js:21:27
parser
https://qy4rp9.csb.app/node_modules/remark-parse/lib/index.js:9:48
Function.parse
```
<img width="1476" alt="image" src="https://github.com/remarkjs/react-markdown/assets/8624194/8314c0f6-a62f-47c3-96d2-77083fec40e8">

### Expected behavior

The table works as well as our official demo
<img width="1778" alt="image" src="https://github.com/remarkjs/react-markdown/assets/8624194/8e3eed8b-298f-440d-96fd-b004bf7ff5a7">

### Actual behavior

Page broken up

### Runtime

Node v16

### Package manager

npm 8, npm 6

### OS

macOS

### Build and bundle tools

Vite

**Comment by wooorm** [comment]
Downgrade for now. There are more than 500 projects. It takes some time for me to update everything.

**Comment by AndyBoat** [comment]
@wooorm  I wonder if there is  anything I can do to help u?

**Comment by wooorm** [comment]
Thanks for offering Andy!
There’s just a *lot* of work. And I am really fast at it. Should be done in around 2 weeks.
But, you can always sponsor us, or try your hand at one of the open issues! https://github.com/search?o=desc&q=is%3Aopen+user%3Amdx-js+user%3Amicromark+user%3Aremarkjs+user%3Arehypejs+user%3Aretextjs+user%3Aunifiedjs+user%3Asyntax-tree+user%3Avfile+&s=created&type=issues

**Comment by wooorm** [comment]
solved in https://github.com/remarkjs/react-markdown/commit/c383a45b75685204a1804ea4361d08d19bbeb1cf, released soon

**Comment by brandonvilla21** [comment]
Hello, is there a 4x version with this fix? I tried 4.0.0 and it's still failing

**Comment by brandonvilla21** [comment]
Got it! I was on v8 for react-markdown. It solved the problem, thank you!!

**Comment by kipavy** [comment]
Hi, I have "react-markdown": "^10.1.0" and "remark-gfm": "^4.0.1" and its still not working

**Comment by remcohaszing** [comment]
@kipavy This should work. If it’s not working, we’re going to need a minimal viable reproduction.

**Comment by kipavy** [comment]
> [@kipavy](https://github.com/kipavy) This should work. If it’s not working, we’re going to need a minimal viable reproduction.

My bad It seems it was an issue with pnpm, I reinstalled everything and it seems to work. Thanks
